fixtures:
  repositories:
    stdlib:
      repo: git://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: 4.3.1
    logrotate:
      repo: git://github.com/rodjek/puppet-logrotate.git
      ref: 1.1.1
    epel:
      repo: git://github.com/stahnma/puppet-module-epel.git
      ref: 0.1.0
    mysql: 
      repo: git://github.com/puppetlabs/puppetlabs-mysql.git
      ref: 2.3.1
    inifile:
      repo: git://github.com/puppetlabs/puppetlabs-inifile
      ref: 1.1.3
    apache:
      repo: git://github.com/puppetlabs/puppetlabs-apache
    concat:
      repo: git://github.com/puppetlabs/puppetlabs-concat.git
  symlinks:
    xdmod: "#{source_dir}"
