fixtures:
  repositories:
    stdlib:
      repo: git://github.com/puppetlabs/puppetlabs-stdlib.git
    logrotate:
      repo: git://github.com/rodjek/puppet-logrotate.git
    epel:
      repo: git://github.com/stahnma/puppet-module-epel.git
    mysql: 
      repo: git://github.com/puppetlabs/puppetlabs-mysql.git
    inifile:
      repo: git://github.com/puppetlabs/puppetlabs-inifile
    apache:
      repo: git://github.com/puppetlabs/puppetlabs-apache
    concat:
      repo: git://github.com/puppetlabs/puppetlabs-concat.git
  symlinks:
    xdmod: "#{source_dir}"
